name: Package Application with Pyinstaller

on:
  push:
    branches: [ '@feature/actions' ]
  pull_request:
    branches: [ '@feature/actions' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v2
      with:
        name: disco-hue
        path: dist/windows